import = ["/home/stahl/.config/alacritty/include/local.toml", "/home/stahl/.config/alacritty/include/colors.toml"]
live_config_reload = true

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[selection]
save_to_clipboard = true
