#!/bin/sh
# use with C-x + one of the following bindings
while read file
do
	case "$1" in
	"C-d")
		trash-put "$file" ;;
	"C-r")
		convert -rotate 90 "$file" "$file" ;;
    "C-f")
		# copy file name to clipboard
        echo -n "$file" | wl-copy ;;
	"C-c")
		# copy image to clipboard
		wl-copy < "$file" ;;
	"C-e")
		gimp "$file" & ;;
	"C-p")
		lp "$file" & ;;
    "C-m")
        mv "$file" ~/pics & ;;
	esac
done

